name = "shinfuri-qraph-net"
pages_build_output_dir = "dist"
compatibility_date = "2025-03-17"

[[kv_namespaces]]
id = "f3efee67f8c44e27b2d5fe8ff945c769"
binding = "shinfuri-floating-point-survey-answer"

[[env.production.kv_namespaces]]
id = "f3efee67f8c44e27b2d5fe8ff945c769"
binding = "shinfuri-floating-point-survey-answer"
